name: srbench-m5gp
channels:
  - rapidsai
  - conda-forge
dependencies:
  - python=3.12
  - cudf=26.06
  - cuml=26.06
  - cugraph=26.06
  - "cuda-version>=12.2,<=12.9"
  - numba
  - numpy
  - pandas
  - scikit-learn
  - sympy
  - pip
  - pip:
      - scikit-cuda
